#!/usr/bin/env bash
set -e

main() {
  if [ $# -ne 9 ]; then
    echo "Usage: tre_environment_name sns_arn s3_bucket_source \
s3_object_bagit s3_object_sha consignment_reference consignment_type \
aws_profile_source aws_profile_target"
    return 1
  fi

  local tre_environment_name="${1:?}"
  local sns_arn="${2:?}"
  local s3_bucket_source="${3:?}"
  local s3_object_bagit="${4:?}"
  local s3_object_sha="${5:?}"
  local consignment_reference="${6:?}"
  local consignment_type="${7:?}"
  local aws_profile_source="${8:-${AWS_PROFILE:?}}"
  local aws_profile_target="${9:-${AWS_PROFILE:?}}"

  printf 'sns_arn="%s"\n' "${sns_arn}"
  printf 'aws_profile_source="%s"\n' "${aws_profile_source}"
  printf 'aws_profile_target="%s"\n' "${aws_profile_target}"

  printf 'AWS S3 listing for source profile "%s":\n' "${aws_profile_source}"
  aws --profile "${aws_profile_source}" s3 ls
  
  printf 'AWS S3 listing for target profile "%s":\n' "${aws_profile_target}"
  aws --profile "${aws_profile_target}" s3 ls

  local s3_path_bagit="s3://${s3_bucket_source}/${s3_object_bagit}"
  printf 'AWS S3 listing for target consignment "%s":\n' "${s3_path_bagit:?}"
  aws --profile "${aws_profile_source}" s3 ls "${s3_path_bagit}"

  local s3_path_sha="s3://${s3_bucket_source}/${s3_object_sha}"
  printf 'AWS S3 listing for target consignment sha "%s":\n' "${s3_path_sha}"
  aws --profile "${aws_profile_source}" s3 ls "${s3_path_sha}"

  local bagit_url
  bagit_url="$(aws --profile "${aws_profile_source}" \
      s3 presign "s3://${s3_bucket_source}/${s3_object_bagit}" \
      --expires-in "${presigned_url_expiry_secs:-60}")"

  local bagit_checksum_url
  bagit_checksum_url="$(aws --profile "${aws_profile_source}" \
      s3 presign "s3://${s3_bucket_source}/${s3_object_sha}" \
      --expires-in "${presigned_url_expiry_secs:-60}")"

  local event_parameter_block
  event_parameter_block="$(
    ./print_bagit_available_block.sh \
        "${consignment_reference}" \
        "${bagit_url}" \
        "${bagit_checksum_url}"
  )"

  printf 'Generated event parameter block:\n%s\n' "${event_parameter_block:?}"

  local test_uuid
  test_uuid="$(uuidgen | tr '[:upper:]' '[:lower:]')"
  local uuid_list='[{"TDR-TEST-UUID": "'"${test_uuid}"'"}]'
  
  message="$( \
    ./print_event.sh \
      "${uuid_list:?}" \
      'TDR-TEST' \
      'Generated by test script' \
      "${consignment_type:?}" \
      "${tre_environment_name:?}" \
      'bagit-available' \
      "${event_parameter_block:?}"
  )"
  
  printf 'Generated Message:\n%s\n' "${message:?}"
  printf 'sns publish...\n'
  aws --profile "${aws_profile_target:?}" sns publish \
    --message "${message:?}" \
    --topic-arn "${sns_arn:?}"
}

main "$@"
